from gpiozero import TonalBuzzer
from gpiozero.tones import Tone
from time import sleep

# Création d'une instance de TonalBuzzer sur la broche 21
buzzer = TonalBuzzer(21)

# Jouer la mélodie de Tétris
buzzer.play(Tone("E3"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.3)
buzzer.play(Tone("D4"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.2)
buzzer.play(Tone("E4"))
sleep(0.3)
buzzer.play(Tone("D4"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("D4"))
sleep(0.1)
buzzer.play(Tone("E4"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.2)
buzzer.play(Tone("E4"))
sleep(0.3)
buzzer.play(Tone("D4"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("E3"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.3)
buzzer.play(Tone("D4"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("B3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.2)
buzzer.play(Tone("E4"))
sleep(0.3)
buzzer.play(Tone("C4"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("A3"))
sleep(0.1)
buzzer.play(Tone("C4"))
sleep(0.2)
buzzer.play(Tone("E4"))
sleep(0.3)
# Arrêt de la mélodie
buzzer.stop()
